WORD_DICT = {
    "NOT_OPT": "not",
    "none": "",
    "sum": "the sumary",
    "max": "the maximum", 
    "min": "the minimum",
    "count": "the number of",
    "avg": "the average",
    "between": "is between",
    "eq": "equal to",
    "=": "equal to",
    ">=": "greater than or equal to",
    "gte": "greater than or equal to",
    "<=": "less than or equal to",
    "lte": "less than or equal to",
    "!=": "not equal to",
    "neq": "not equal to",
    ">": "greater than",
    "gt": "greater than",
    "<": "less than",
    "lt": "less than",
    "not": "not",
    "in": "in",
    "like": "like",
    "except": "except",
    "union": "or",
    "intersect": "and",
    "desc_limit_1": "the maximum",
    "asc_limit_1": "the minimum",
    "desc_limit_n": "the top",
    "asc_limit_n": "the lowest",
    "asc": "in ascending order of",
    "desc": "in descending order of",
    "and": "and",
    "or": "or",
    "of": "of",
    "all": "",
    "where": "that",
    "the": "the",
    "comma": ",",
    "what": "what are",
    "from": "from",
    "having": "that",
    "groupby": "of different",
    "orderby": "ordered by",
    "orderby_limit": "that have",
    "-": "minus",
    "+": "plus",
    "*": "multiple",
    "/": "divided by",
    "?": "?"
}